---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayane-osiruko
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ayane-osiruko
  replicas: 1
  template:
    metadata:
      labels:
        app: ayane-osiruko
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: registry.uniproject.jp/ayane/osiruko-server:0.1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: default-port
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
            requests:
              memory: "1Gi"
              cpu: "100m"
          env:
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: CLIENT_ID
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: CLIENT_SECRET
            - name: redirect_url
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: REDIRECT_URL
            - name: POSTGRES_HOST
              value: "ayane-osiruko-db"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_PASSWORD
