---
apiVersion: v1
kind: Service
metadata:
  name: ayane-osiruko
spec:
  selector:
    app: ayane-osiruko
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ayane-osiruko-db
spec:
  selector:
    app: osiruko-db
  ports:
    - port: 5432
      targetPort: 5432
